<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.frotoma.jobc</groupId>
  <artifactId>jobc_driver</artifactId>
  <version>0.0.1</version>

  <name>jobc_driver</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.frotoma.com</url>
  <description>
Jobc (java ontology base connection)

LOD, Apache Jena Fuseki, Virtuoso can be used in Java just like JDBC.

Features
- Execute Sparql on ontology repositories by coding like a general Database Connection.
- PoolManager is available. (LOD and Fuseki do not manage the actual pool).
- Can be used like Mybatis.
- The same Sparql can be used in LOD, Jena fuseki, and Virtuoso. When using Preparedstatement, '? ' is used as a variable in Sparql just like in Sql.
- When using preparedstatement in Virtuoso, Sparql uses a different method.
    - e.g.) Use parameters as '??' or use 'INSERT INTO GRAPH' for 'INSERT Data'.
- Generally, LOD does not support updates.
  </description>
  

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>

  <dependencies>
    <!-- jena -->
    <dependency>
        <groupId>org.apache.jena</groupId>
        <artifactId>apache-jena-libs</artifactId>
        <type>pom</type>
        <version>6.2.0</version>
        <exclusions>
            <exclusion>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient-cache</artifactId>
            </exclusion>
        </exclusions>        
    </dependency> 
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20211205</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.13</version>
    </dependency>    
                  
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.36</version>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-api</artifactId>
        <version>2.24.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>2.24.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-slf4j-impl</artifactId>
        <version>2.24.1</version>
    </dependency>
    <!-- virtuoso -->
    <dependency>
        <groupId>unofficial.com.openlink</groupId>
        <artifactId>virtuoso-jdbc</artifactId>
        <version>43.3.119</version>
    </dependency>
    <!--
    <dependency>
        <groupId>virtuoso</groupId>
        <artifactId>virtuoso</artifactId>
        <version>3</version>
        <classifier>virtuoso</classifier>        
    </dependency>
    <dependency>
        <groupId>virtuoso</groupId>
        <artifactId>virtuosojdbc</artifactId>
        <version>4</version>        
    </dependency>     
    -->
    
    <!-- =============== Test =============== -->
    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
      <version>2.7.9</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-dbcp2</artifactId>
      <version>2.9.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.mybatis</groupId>
        <artifactId>mybatis</artifactId>
        <version>3.5.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <repositories>    
    <repository>
        <id>virtuoso</id>
        <name>Openlink Virtuoso drivers packages</name>
        <url>https://maven.pkg.github.com/jeremiehuchet/virtuoso-drivers</url>
    </repository>
  </repositories>
  
  <build>
    <pluginManagement>      
      <plugins>        
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.8.1</version> 
            <executions>
                <execution>
                    <id>copy-dependencies</id>
                    <phase>package</phase> 
                    <goals>
                        <goal>copy-dependencies</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        <includeScope>runtime</includeScope>
                    </configuration>
                </execution>
            </executions>
        </plugin>                
      </plugins>
    </pluginManagement>    
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
