rdf.driver=com.frotoma.jobc.JobcDriver
#rdf.url=jobc:web:http://localhost:8091/sparql&method=get
#rdf.user=master
#rdf.password=1234

rdf.url=jobc:fuseki:http://localhost:3030/mofaservice/sparql&method=post
rdf.user=admin
rdf.password=1234

#rdf.url=jobc:virtuoso://localhost:1111/CHARSET=UTF-8
#rdf.user=dba
#rdf.password=dba

#virtuoso \ub4dc\ub77c\uc774\ubc84 \uc6d0\ubcf8
#rdf.driver=virtuoso.jdbc4.Driver
#rdf.url=jdbc:virtuoso://192.168.10.4:1111/CHARSET=UTF-8
#rdf.user=dba
#rdf.password=dba