/*
MIT License

Copyright (c) 2026 jongearl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 
  Virtuoso의 PreparedStatement 대신에 Statement를 실행함
*/
package com.frotoma.jobc.virt;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class VirtuosoConnection implements Connection {
    
    private final Connection delegate;

    public VirtuosoConnection(Connection delegate) {
        this.delegate = delegate;        
    }

    // prepareStatement 모든 오버로드 변환 적용
    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {        
        return new VirtuosoPreparedStatement( delegate.createStatement(),   sql );
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency) throws SQLException {
        return new VirtuosoPreparedStatement(delegate.createStatement(), sql, resultSetType, resultSetConcurrency );        
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        return new VirtuosoPreparedStatement(delegate.createStatement(), sql, resultSetType, resultSetConcurrency , resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        return new VirtuosoPreparedStatement(delegate.createStatement(), sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
            throws SQLException {
        return new VirtuosoPreparedStatement(delegate.createStatement(), sql, columnIndexes);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames)
            throws SQLException {
        return new VirtuosoPreparedStatement(delegate.createStatement(), sql, columnNames);
    }

    // 나머지 Connection 메서드 위임
    @Override public Statement createStatement() throws SQLException { 
        return new VirtuosoStatement(delegate.createStatement());  
    }
    @Override public CallableStatement prepareCall(String sql) throws SQLException { return delegate.prepareCall(sql); }
    @Override public String nativeSQL(String sql) throws SQLException { return delegate.nativeSQL(sql); }
    @Override public void setAutoCommit(boolean a) throws SQLException { delegate.setAutoCommit(a); }
    @Override public boolean getAutoCommit() throws SQLException { return delegate.getAutoCommit(); }
    @Override public void commit() throws SQLException { delegate.commit(); }
    @Override public void rollback() throws SQLException { delegate.rollback(); }
    @Override public void close() throws SQLException { delegate.close(); }
    @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
    @Override public DatabaseMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
    @Override public void setReadOnly(boolean r) throws SQLException { delegate.setReadOnly(r); }
    @Override public boolean isReadOnly() throws SQLException { return delegate.isReadOnly(); }
    @Override public void setCatalog(String c) throws SQLException { delegate.setCatalog(c); }
    @Override public String getCatalog() throws SQLException { return delegate.getCatalog(); }
    @Override public void setTransactionIsolation(int l) throws SQLException { delegate.setTransactionIsolation(l); }
    @Override public int getTransactionIsolation() throws SQLException { return delegate.getTransactionIsolation(); }
    @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
    @Override public Statement createStatement(int t, int c) throws SQLException { return delegate.createStatement(t, c); }
    @Override public CallableStatement prepareCall(String s, int t, int c) throws SQLException { return delegate.prepareCall(s, t, c); }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return delegate.getTypeMap(); }
    @Override public void setTypeMap(Map<String, Class<?>> m) throws SQLException { delegate.setTypeMap(m); }
    @Override public void setHoldability(int h) throws SQLException { delegate.setHoldability(h); }
    @Override public int getHoldability() throws SQLException { return delegate.getHoldability(); }
    @Override public Savepoint setSavepoint() throws SQLException { return delegate.setSavepoint(); }
    @Override public Savepoint setSavepoint(String n) throws SQLException { return delegate.setSavepoint(n); }
    @Override public void rollback(Savepoint s) throws SQLException { delegate.rollback(s); }
    @Override public void releaseSavepoint(Savepoint s) throws SQLException { delegate.releaseSavepoint(s); }
    @Override public Statement createStatement(int t, int c, int h) throws SQLException { return delegate.createStatement(t, c, h); }
    @Override public CallableStatement prepareCall(String s, int t, int c, int h) throws SQLException { return delegate.prepareCall(s, t, c, h); }
    @Override public Clob createClob() throws SQLException { return delegate.createClob(); }
    @Override public Blob createBlob() throws SQLException { return delegate.createBlob(); }
    @Override public NClob createNClob() throws SQLException { return delegate.createNClob(); }
    @Override public SQLXML createSQLXML() throws SQLException { return delegate.createSQLXML(); }
    @Override public boolean isValid(int t) throws SQLException { return delegate.isValid(t); }
    @Override public void setClientInfo(String n, String v) throws SQLClientInfoException { delegate.setClientInfo(n, v); }
    @Override public void setClientInfo(Properties p) throws SQLClientInfoException { delegate.setClientInfo(p); }
    @Override public String getClientInfo(String n) throws SQLException { return delegate.getClientInfo(n); }
    @Override public Properties getClientInfo() throws SQLException { return delegate.getClientInfo(); }
    @Override public Array createArrayOf(String t, Object[] e) throws SQLException { return delegate.createArrayOf(t, e); }
    @Override public Struct createStruct(String t, Object[] a) throws SQLException { return delegate.createStruct(t, a); }
    @Override public void setSchema(String s) throws SQLException { delegate.setSchema(s); }
    @Override public String getSchema() throws SQLException { return delegate.getSchema(); }
    @Override public void abort(Executor e) throws SQLException { delegate.abort(e); }
    @Override public void setNetworkTimeout(Executor e, int ms) throws SQLException { delegate.setNetworkTimeout(e, ms); }
    @Override public int getNetworkTimeout() throws SQLException { return delegate.getNetworkTimeout(); }
    @Override public <T> T unwrap(Class<T> i) throws SQLException { return delegate.unwrap(i); }
    @Override public boolean isWrapperFor(Class<?> i) throws SQLException { return delegate.isWrapperFor(i); }
}