/*
MIT License

Copyright (c) 2026 jongearl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */
package com.frotoma.jobc.virt;

import com.frotoma.jobc.builder.LogBuilder;
import com.frotoma.jobc.builder.PrepareSparqlBuilder;
import com.frotoma.jobc.builder.VirtuosoPreparedSparqlBuilder;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import org.apache.jena.irix.IRIx;
import org.apache.jena.rdf.model.Literal;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * TODO : Virtuoso Preparedstatement
 */
public class VirtuosoPreparedStatement4psmt implements PreparedStatement {

    private Logger logger = LogManager.getLogger(VirtuosoPreparedStatement4psmt.class);

    // 수정부분
    private final Connection conn;
    private final VirtuosoPreparedSparqlBuilder builder;
    private final Map<Integer,Object> parameterValues = new HashMap<>();
    private PreparedStatement pstmt;
    // 수정부분
    
    // prepareStatement 오버로드별 추가 파라미터
    private Integer resultSetType;
    private Integer resultSetConcurrency;
    private Integer resultSetHoldability;
    private Integer autoGeneratedKeys;
    private Integer[] columnIndexes;
    private String[] columnNames;

    // 어떤 prepareStatement 오버로드로 생성됐는지 구분
    private enum PrepareMode {
        DEFAULT,
        TYPE_CONCURRENCY,
        TYPE_CONCURRENCY_HOLDABILITY,
        AUTO_GENERATED_KEYS,
        COLUMN_INDEXES,
        COLUMN_NAMES
    }
    private PrepareMode prepareMode;
    

    // ---------------------------------------------------------------
    // 생성자
    // ---------------------------------------------------------------
    
    /** 기본 생성자 — prepareStatement(String sql) */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql) throws SQLException {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.DEFAULT;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    /**
     * prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql,
     *       ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
     */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql,
                                          int resultSetType,
                                          int resultSetConcurrency) {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.TYPE_CONCURRENCY;
        this.resultSetType        = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    /**
     * prepareStatement(String sql, int resultSetType,
     *                  int resultSetConcurrency, int resultSetHoldability)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql,
     *       ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY,
     *       ResultSet.HOLD_CURSORS_OVER_COMMIT);
     */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql,
                                          int resultSetType,
                                          int resultSetConcurrency,
                                          int resultSetHoldability) {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.TYPE_CONCURRENCY_HOLDABILITY;
        this.resultSetType        = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = resultSetHoldability;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    /**
     * prepareStatement(String sql, int autoGeneratedKeys)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, Statement.RETURN_GENERATED_KEYS);
     */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql,
                                          int autoGeneratedKeys) {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.AUTO_GENERATED_KEYS;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = autoGeneratedKeys;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    /**
     * prepareStatement(String sql, int[] columnIndexes)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, new int[]{1, 2});
     */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql,
                                          int[] columnIndexes) {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.COLUMN_INDEXES;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        //this.columnIndexes        = columnIndexes;
        this.columnNames          = null;
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    /**
     * prepareStatement(String sql, String[] columnNames)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, new String[]{"id", "name"});
     */
    public VirtuosoPreparedStatement4psmt(Connection conn, String sql,
                                          String[] columnNames) {
        this.conn                 = conn;
        this.prepareMode          = PrepareMode.COLUMN_NAMES;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = columnNames;
        this.builder = new VirtuosoPreparedSparqlBuilder();
        this.builder.setQuery(sql);
    }

    // ---------------------------------------------------------------
    // executeQuery / executeUpdate / execute — PrepareMode 반영
    // ---------------------------------------------------------------
    
    private void setParameterValues() throws SQLException{
        Iterator<Integer> indexIt = parameterValues.keySet().iterator();
        
        while( indexIt.hasNext() ){
            Integer i = indexIt.next();
            Object param = parameterValues.get(i);
            
            logger.debug("[Virtuoso] Sparql Param : " + i +" = "+ param);
        
            if( param instanceof String ){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setString(i, (String)param);                
            }else if(param instanceof URL){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setURL(i, (URL)param);
            }else if(param instanceof Boolean){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setBoolean(i, (Boolean)param);
            }else if(param instanceof Integer){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setInt(i, (Integer)param);
            }else if(param instanceof Float){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setFloat(i, (Float)param);
            }else if(param instanceof Double){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setDouble(i, (Double)param);
            }else if(param instanceof IRIx){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );                
                this.pstmt.setString(i, ((IRIx)param).toString());
            }else if(param instanceof Calendar){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setObject(i, (Calendar)param);
            }else if(param instanceof Literal){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setObject(i, (Literal)param);
            }else if(param instanceof Long){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setObject(i, (Long)param);
            }else{
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                this.pstmt.setObject(i, param);            
            }            
        }        
    }

    @Override
    public ResultSet executeQuery() throws SQLException {        
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt == null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeQuery();
    }

    @Override
    public int executeUpdate() throws SQLException {
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt == null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeUpdate();
    }

    @Override
    public boolean execute() throws SQLException {
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt == null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        switch (prepareMode) {
            case AUTO_GENERATED_KEYS:
                return pstmt.execute(virtuosoSparql, autoGeneratedKeys);
            case COLUMN_INDEXES:
                
                int[] intColumnIndexs = new int[columnIndexes.length];
                for( Integer value : columnIndexes){
                    intColumnIndexs[value] = columnIndexes[value];
                }
                return pstmt.execute(virtuosoSparql, intColumnIndexs);
            case COLUMN_NAMES:
                return pstmt.execute(virtuosoSparql, columnNames);
            default:
                return pstmt.execute(virtuosoSparql);
        }        
    }
    
    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        return pstmt.getResultSet().getMetaData();
    }

    @Override
    public void addBatch() throws SQLException {
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        pstmt.addBatch(virtuosoSparql);
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {        
        return pstmt.getParameterMetaData();
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        this.parameterValues.put(parameterIndex, "");
        this.builder.addParameter(parameterIndex, "");        
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);          
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {             
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException {        
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
        
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();        
    }

    @Override
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();        
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void clearParameters() throws SQLException {
        //queryBuilder.clearParameters();        
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }
    

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);            
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);            
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);                
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        this.parameterValues.put(parameterIndex, "");
        this.builder.addParameter(parameterIndex, "");         
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        this.parameterValues.put(parameterIndex, x);
        this.builder.addParameter(parameterIndex, x);        
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        this.parameterValues.put(parameterIndex, value);
        this.builder.addParameter(parameterIndex, value);        
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
     
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {       
        
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeQuery(virtuosoSparql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {        
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeUpdate(virtuosoSparql);
    }

    @Override
    public void close() throws SQLException {
        pstmt.close();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {        
        return pstmt.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        pstmt.setMaxFieldSize(max);        
    }

    @Override
    public int getMaxRows() throws SQLException {        
        return pstmt.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {        
        pstmt.setMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        pstmt.setEscapeProcessing(enable);        
    }

    @Override
    public int getQueryTimeout() throws SQLException {        
        return pstmt.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        pstmt.setQueryTimeout(seconds);        
    }

    @Override
    public void cancel() throws SQLException {
        pstmt.cancel();
        
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {        
        return pstmt.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        pstmt.clearWarnings();        
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        pstmt.setCursorName(name);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        return pstmt.execute(sql);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {        
        return pstmt.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return pstmt.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {        
        return pstmt.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        pstmt.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return pstmt.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        pstmt.setFetchSize(rows);        
    }

    @Override
    public int getFetchSize() throws SQLException {
        return pstmt.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return pstmt.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return pstmt.getResultSetType();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        pstmt.addBatch(sql);        
    }

    @Override
    public void clearBatch() throws SQLException {
        pstmt.clearBatch();        
    }

    @Override
    public int[] executeBatch() throws SQLException {        
        return pstmt.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return pstmt.getConnection();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return pstmt.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return pstmt.getGeneratedKeys();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {        
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeUpdate(virtuosoSparql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeUpdate(virtuosoSparql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.executeUpdate(virtuosoSparql, columnNames);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.execute(virtuosoSparql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.execute(virtuosoSparql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        this.builder.setQuery(sql);
        
        String virtuosoSparql = this.builder.query();
        
        logger.debug("[Virtuoso] Sparql : " + virtuosoSparql);
        
        if( this.pstmt != null ){
            this.pstmt = conn.prepareStatement(virtuosoSparql);
        }
        
        setParameterValues();
        
        return this.pstmt.execute(virtuosoSparql, columnNames);
    }

    @Override
    public int getResultSetHoldability() throws SQLException {        
        return pstmt.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return pstmt.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        pstmt.setPoolable(poolable);        
    }

    @Override
    public boolean isPoolable() throws SQLException {        
        return pstmt.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        pstmt.closeOnCompletion();        
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {        
        return pstmt.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {        
        return pstmt.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return pstmt.isWrapperFor(iface);
    }
}