/*
MIT License

Copyright (c) 2026 jongearl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
 */
package com.frotoma.jobc.virt;

import com.frotoma.jobc.builder.LogBuilder;
import com.frotoma.jobc.builder.PrepareSparqlBuilder;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import org.apache.jena.irix.IRIx;
import org.apache.jena.rdf.model.Literal;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * 실제로는 Statement를 시행함
 */
public class VirtuosoPreparedStatement implements PreparedStatement {

    private Logger logger = LogManager.getLogger(VirtuosoPreparedStatement.class);

    private final Statement stmt;
    private final String sql;

    // prepareStatement 오버로드별 추가 파라미터
    private final int resultSetType;
    private final int resultSetConcurrency;
    private final int resultSetHoldability;
    private final int autoGeneratedKeys;
    private final int[] columnIndexes;
    private final String[] columnNames;

    // 어떤 prepareStatement 오버로드로 생성됐는지 구분
    private enum PrepareMode {
        DEFAULT,
        TYPE_CONCURRENCY,
        TYPE_CONCURRENCY_HOLDABILITY,
        AUTO_GENERATED_KEYS,
        COLUMN_INDEXES,
        COLUMN_NAMES
    }
    private final PrepareMode prepareMode;
    
    private PrepareSparqlBuilder queryBuilder = null;

    // 파라미터 값 저장
    private final List<Object> params = new ArrayList<>();
    
    

    // ---------------------------------------------------------------
    // 생성자
    // ---------------------------------------------------------------
    
    /** 기본 생성자 — prepareStatement(String sql) */
    public VirtuosoPreparedStatement(Statement stmt, String sql) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);        
        this.prepareMode          = PrepareMode.DEFAULT;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    /**
     * prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql,
     *       ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
     */
    public VirtuosoPreparedStatement(Statement stmt, String sql,
                                          int resultSetType,
                                          int resultSetConcurrency) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);
        this.prepareMode          = PrepareMode.TYPE_CONCURRENCY;
        this.resultSetType        = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    /**
     * prepareStatement(String sql, int resultSetType,
     *                  int resultSetConcurrency, int resultSetHoldability)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql,
     *       ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY,
     *       ResultSet.HOLD_CURSORS_OVER_COMMIT);
     */
    public VirtuosoPreparedStatement(Statement stmt, String sql,
                                          int resultSetType,
                                          int resultSetConcurrency,
                                          int resultSetHoldability) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);
        this.prepareMode          = PrepareMode.TYPE_CONCURRENCY_HOLDABILITY;
        this.resultSetType        = resultSetType;
        this.resultSetConcurrency = resultSetConcurrency;
        this.resultSetHoldability = resultSetHoldability;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    /**
     * prepareStatement(String sql, int autoGeneratedKeys)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, Statement.RETURN_GENERATED_KEYS);
     */
    public VirtuosoPreparedStatement(Statement stmt, String sql,
                                          int autoGeneratedKeys) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);
        this.prepareMode          = PrepareMode.AUTO_GENERATED_KEYS;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = autoGeneratedKeys;
        this.columnIndexes        = null;
        this.columnNames          = null;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    /**
     * prepareStatement(String sql, int[] columnIndexes)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, new int[]{1, 2});
     */
    public VirtuosoPreparedStatement(Statement stmt, String sql,
                                          int[] columnIndexes) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);
        this.prepareMode          = PrepareMode.COLUMN_INDEXES;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = columnIndexes;
        this.columnNames          = null;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    /**
     * prepareStatement(String sql, String[] columnNames)
     *
     * 호출 예:
     *   new VirtuosoPreparedStatementProxy(stmt, sql, new String[]{"id", "name"});
     */
    public VirtuosoPreparedStatement(Statement stmt, String sql,
                                          String[] columnNames) {
        this.stmt                 = stmt;
        this.sql                  = convert(sql);
        this.prepareMode          = PrepareMode.COLUMN_NAMES;
        this.resultSetType        = ResultSet.TYPE_FORWARD_ONLY;
        this.resultSetConcurrency = ResultSet.CONCUR_READ_ONLY;
        this.resultSetHoldability = ResultSet.CLOSE_CURSORS_AT_COMMIT;
        this.autoGeneratedKeys    = Statement.NO_GENERATED_KEYS;
        this.columnIndexes        = null;
        this.columnNames          = columnNames;
        this.queryBuilder = new PrepareSparqlBuilder(this.sql);
    }

    // ---------------------------------------------------------------
    // SQL 변환
    // ---------------------------------------------------------------

    private String convert(String sql) {
        if (sql == null) return null;
        String trimmed = sql.trim();        
        if (!trimmed.toUpperCase().startsWith("SPARQL")) {
            trimmed = "SPARQL " + trimmed;
        }        
        logger.info("[Virtuoso] PreparedStatement : " + LogBuilder.generateOneline(trimmed));
        return trimmed;
    }

    private String replaceParams(String sql) {
        StringBuilder result = new StringBuilder();
        boolean inSingleQuote = false;
        boolean inDoubleQuote = false;

        for (int i = 0; i < sql.length(); i++) {
            char c = sql.charAt(i);

            if (c == '\'' && !inDoubleQuote) {
                inSingleQuote = !inSingleQuote;
                result.append(c);
            } else if (c == '"' && !inSingleQuote) {
                inDoubleQuote = !inDoubleQuote;
                result.append(c);
            } else if (c == '?' && !inSingleQuote && !inDoubleQuote) {
                boolean nextIsLetter = (i + 1 < sql.length())
                        && Character.isLetter(sql.charAt(i + 1));
                if (nextIsLetter) {
                    result.append(c);           // ?name 등 SPARQL 변수 → 그대로
                } else {
                    result.append("??");        // 단독 ? → MyBatis 파라미터 → ??
                }
            } else {
                result.append(c);
            }
        }
        return result.toString();
    }

    // ---------------------------------------------------------------
    // buildSql — PrepareMode에 따라 executeUpdate/execute 오버로드 선택
    // ---------------------------------------------------------------

    /*
    private String buildSql() {
        String result = sql;
        PrepareSparqlBuilder builder = new PrepareSparqlBuilder(sql);        
        int i = 1;
        for (Object param : params) {
            if( param instanceof String ){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (String)param);
            }else if(param instanceof URL){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (URL)param);
            }else if(param instanceof Boolean){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Boolean)param);
            }else if(param instanceof Integer){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Integer)param);
            }else if(param instanceof Float){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Float)param);
            }else if(param instanceof Double){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Double)param);
            }else if(param instanceof IRIx){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (URL)param);
            }else if(param instanceof Calendar){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Calendar)param);
            }else if(param instanceof Literal){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Literal)param);
            }else if(param instanceof Long){
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, (Long)param);
            }else{
                logger.info("[Virtuoso] SPARQL PARAM : " + param );
                builder.addParameter(i, param);            
            }
            i++;
        }
        result = builder.query();
        logger.info("[Virtuoso] SPARQL : " + LogBuilder.generateOneline(result));
        return result;
    }
    */

    // ---------------------------------------------------------------
    // executeQuery / executeUpdate / execute — PrepareMode 반영
    // ---------------------------------------------------------------

    @Override
    public ResultSet executeQuery() throws SQLException {        
        logger.debug("[Virtuoso] Sparql : " + this.queryBuilder.query());
        return stmt.executeQuery(this.queryBuilder.query());
    }

    @Override
    public int executeUpdate() throws SQLException {        
        logger.debug("[Virtuoso] Sparql : " + this.queryBuilder.query());
        switch (prepareMode) {
            case AUTO_GENERATED_KEYS:
                return stmt.executeUpdate(this.queryBuilder.query(), autoGeneratedKeys);
            case COLUMN_INDEXES:
                return stmt.executeUpdate(this.queryBuilder.query(), columnIndexes);
            case COLUMN_NAMES:
                return stmt.executeUpdate(this.queryBuilder.query(), columnNames);
            default:
                return stmt.executeUpdate(this.queryBuilder.query());
        }
    }

    @Override
    public boolean execute() throws SQLException {
        logger.debug("[Virtuoso] Sparql : " + this.queryBuilder.query());
        switch (prepareMode) {
            case AUTO_GENERATED_KEYS:
                return stmt.execute(this.queryBuilder.query(), autoGeneratedKeys);
            case COLUMN_INDEXES:
                return stmt.execute(this.queryBuilder.query(), columnIndexes);
            case COLUMN_NAMES:
                return stmt.execute(this.queryBuilder.query(), columnNames);
            default:
                return stmt.execute(this.queryBuilder.query());
        }
    }
    
    @Override
    public ResultSetMetaData getMetaData() throws SQLException {
        return stmt.getResultSet().getMetaData();
    }

    @Override
    public void addBatch() throws SQLException {
        stmt.addBatch(queryBuilder.query());
    }

    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        queryBuilder.addParameter(parameterIndex , "");        
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);        
    }

    @Override
    public void setByte(int parameterIndex, byte x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);        
    }

    @Override
    public void setShort(int parameterIndex, short x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);        
    }

    @Override
    public void setInt(int parameterIndex, int x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);                
    }

    @Override
    public void setLong(int parameterIndex, long x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);        
    }

    @Override
    public void setFloat(int parameterIndex, float x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setDouble(int parameterIndex, double x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);        
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setString(int parameterIndex, String x) throws SQLException {             
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setDate(int parameterIndex, Date x) throws SQLException {        
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setTime(int parameterIndex, Time x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
        
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);   
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();        
    }

    @Override
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();        
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void clearParameters() throws SQLException {
        //queryBuilder.clearParameters();        
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setObject(int parameterIndex, Object x) throws SQLException {                
        queryBuilder.addParameter(parameterIndex , x);        
    }
    

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setArray(int parameterIndex, Array x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    

    @Override
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);                
    }

    @Override
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);                
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);                
    }

    @Override
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        queryBuilder.addParameter(parameterIndex , "");        
    }

    @Override
    public void setURL(int parameterIndex, URL x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        queryBuilder.addParameter(parameterIndex , x);
    }

    @Override
    public void setNString(int parameterIndex, String value) throws SQLException {
        queryBuilder.addParameter(parameterIndex , value);
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
     
    }

    @Override
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        throw new UnsupportedOperationException();
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {        
        return stmt.executeQuery(sql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {        
        return stmt.executeUpdate(sql);
    }

    @Override
    public void close() throws SQLException {
        stmt.close();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {        
        return stmt.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        stmt.setMaxFieldSize(max);        
    }

    @Override
    public int getMaxRows() throws SQLException {        
        return stmt.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {        
        stmt.setMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        stmt.setEscapeProcessing(enable);        
    }

    @Override
    public int getQueryTimeout() throws SQLException {        
        return stmt.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        stmt.setQueryTimeout(seconds);        
    }

    @Override
    public void cancel() throws SQLException {
        stmt.cancel();
        
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {        
        return stmt.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        stmt.clearWarnings();        
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        stmt.setCursorName(name);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        return stmt.execute(sql);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {        
        return stmt.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return stmt.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {        
        return stmt.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        stmt.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return stmt.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        stmt.setFetchSize(rows);        
    }

    @Override
    public int getFetchSize() throws SQLException {
        return stmt.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return stmt.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return stmt.getResultSetType();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        stmt.addBatch(sql);        
    }

    @Override
    public void clearBatch() throws SQLException {
        stmt.clearBatch();        
    }

    @Override
    public int[] executeBatch() throws SQLException {        
        return stmt.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return stmt.getConnection();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return stmt.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return stmt.getGeneratedKeys();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {        
        return stmt.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return stmt.executeUpdate(sql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return stmt.executeUpdate(sql, columnNames);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return stmt.execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return stmt.execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return stmt.execute(sql, columnNames);
    }

    @Override
    public int getResultSetHoldability() throws SQLException {        
        return stmt.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return stmt.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        stmt.setPoolable(poolable);        
    }

    @Override
    public boolean isPoolable() throws SQLException {        
        return stmt.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        stmt.closeOnCompletion();        
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {        
        return stmt.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {        
        return stmt.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return stmt.isWrapperFor(iface);
    }
}